services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml-web
    volumes:
      - ./artifacts:/app/artifacts
      - ./mlruns:/app/mlruns
      - ./logs:/app/logs
    ports:
      - "8080:8080"