apiVersion: v1
kind: Service
metadata:
  name: tap30-challenge-mlops
  namespace: tap30
  labels:
    app: tap30-challenge-mlops
spec:
  type: LoadBalancer
  selector:
    app: tap30-challenge-mlops
  ports:
  - name: web
    port: 80
    targetPort: 8080

